# Generated by Django 4.0 on 2021-12-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topping', models.CharField(blank=True, max_length=200, null=True)),
                ('diameter', models.IntegerField(blank=True, choices=[(23, '23 cм'), (30, '30 cм'), (35, '35 cм'), (40, '40 cм')], null=True)),
            ],
            options={
                'db_table': 'pizza',
                'managed': False,
            },
        ),
    ]
